---
namespace: 'r_pufky'
name: 'media'
version: '1.0.0'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Media management and streaming services for ansible.
license_file: 'LICENSE'
tags:
  - 'media'
  - 'stream'
  - 'streaming'
  - 'management'
  - 'linux'
  - 'tools'
  - 'networking'
# Update all collections with dependency changes.
dependencies:
  'r_pufky.data': '>=3.2.0,<4.0.0'
  'r_pufky.deb': '>=4.0.0,<5.0.0'
  'ansible.posix': '>=2.1.0,<3.0.0'
  'community.general': '>=12.4.0,<13.0.0'

repository: 'https://github.com/r-pufky/ansible_collection_media'
documentation: 'https://r-pufky.github.io/ansible_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_media'
issues: 'https://github.com/r-pufky/ansible_collection_media/issues'

# Do not include: testing, environments, caches, IDE settings, or staging
# messages in release tarball.
build_ignore:
  - '*.ansible'
  - '*.gitignore'
  - '*.gitattributes'
  - '*.gitmodules'
  - '*.git'
  - '*.venv'
  - '*.envrc'
  - '*.vscode'
  - '*molecule'
  - 'ansible.env'
  - 'pyproject.toml'
  - 'uv.lock'
  - 'TODO.md'
  - 'COMMIT.md'
